# Generated by Django 3.0.7 on 2020-09-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requirements', '0003_help_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_requirements.Donor')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_requirements.Requirement')),
            ],
        ),
    ]
