# Generated by Django 3.0.7 on 2020-09-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requirements', '0005_auto_20200927_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='beds',
            field=models.IntegerField(default=0, verbose_name='Number of beds'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='kits',
            field=models.IntegerField(default=0, verbose_name='Number of kits'),
        ),
    ]
