# Generated by Django 3.0.7 on 2020-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requirements', '0002_requirement_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_category', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
