# Generated by Django 3.0.7 on 2020-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requirements', '0003_auto_20200927_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_fulfilled',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
