# Generated by Django 3.0.7 on 2020-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requirements', '0005_requirement_fulfilled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='amount',
            field=models.IntegerField(max_length=999999, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='quantity',
            field=models.IntegerField(max_length=999999, null=True),
        ),
    ]
