# Generated by Django 3.0.7 on 2020-09-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requirements', '0006_auto_20200927_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_fulfilled',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
